export const SET_SINGER = 'SET_SINGER'

export const SET_PLAYING_STATE = 'SET_PLAYING_STATE'

export const SET_FULL_SREEN = 'SET_FULL_SREEN'

export const SET_PLAYLIST = 'SET_PLAYLIST'

export const SET_SEQUNCE_LIST = 'SET_SEQUNCE_LIST'

export const SET_PLAY_MODE = 'SET_PLAY_MODE'

export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'

export const SET_DISC = 'SET_DISC'
